name: Build and deploy - easyurlfe

on:
  workflow_dispatch:
  # push:
  #  branches:
  #    - main
  # pull_request:
  #  types: [opened, synchronize, reopened, closed]
  #  branches:
  #    - main

jobs:
  build_and_deploy:
    # if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    name: Build and Deploy Job
    
    env:
    #  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      APP_LOCATION: "/" # location of your client code
      API_LOCATION: "api" # location of your api source code - optional
      APP_ARTIFACT_LOCATION: "build" # location of client code build output
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          # skip_app_build: true

  # close_pull_request_job:
  #  if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #  runs-on: ubuntu-latest
  #  name: Close Pull Request Job
  #  steps:
  #    - name: Close Pull Request
  #      id: closepullrequest
  #      uses: Azure/static-web-apps-deploy@v1
  #      with:
  #        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  #        action: "close"
